version: '3'
services:
  db:
    build: .
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - "3307:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
